### ISSUE TITLE
There are more recent changes, mind pushing up another build?

### ISSUE THREAD

**Issue by jonahbron** [jfyne/docker-grpcwebproxy#1]
:)

**Comment by jonahbron** [comment]
Actually don't yet, there's a breaking bug in the current version.

https://github.com/improbable-eng/grpc-web/issues/145

**Comment by n0mer** [comment]
@jonahbron improbable-eng/grpc-web#145 is closed

@jfyne FYI

**Comment by jfyne** [comment]
Ok so this is fixed upstream

**Comment by jonahbron** [comment]
Thanks @jfyne !
